language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - ingvild.broen@gmail.com
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
